[project]
name = "bacte"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "litestar[jinja,standard]>=2.17.0",
    "openpyxl>=3.1.5",
    "polars>=1.33.1",
]

[tool.pyright]
typeCheckingMode = "strict"
